### ISSUE TITLE
[Bug] In Twitter the "Download Image" doesn't work

### ISSUE THREAD

**Issue by JavierJiaCDUT** [tw93/Pake#601]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

I download the dmg from: https://github.com/tw93/Pake/releases/latest/download/Twitter.dmgdownloaded

### System version

macOS 14.1.1 (23B81)

### Node.js version

node: stable 21.2.0 (bottled), HEAD

### Minimal reproduce step

When I try to save the image in Twitter post, there is no response on "Download Image"

### What did you expect to see?

When I click the "Download Image" it should call up the finder and select the path to download 

### What did you see instead?

Nothing happened

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jeasonnow** [comment]
I think this is due to Tauri using the system's built-in webview, and the context menu handling is provided by default by the webview. I found a lot of related issues in Apple's developer community.

https://developer.apple.com/forums/thread/75140
https://developer.apple.com/forums/thread/77789
https://developer.apple.com/forums/thread/671454

Currently, we probably can't handle this scenario in Pake.

**Comment by JavierJiaCDUT** [comment]
Sorry to hear that, is that possible mentioned in the doc thus the user may know this issue?
