### ISSUE TITLE
[Bug] Not working with Fish shell

### ISSUE THREAD

**Issue by d0sse** [tw93/Pake#714]
### Pake version

2.5.1

### System version

macOS Sonoma 14.5

### Node.js version

20.13.1

### Minimal reproduce step

try to build app

`pake web.skype.com --icon xxx.icns`

### What did you expect to see?

app building

### What did you see instead?

following error:
```
 pake-cli@2.5.1 tauri
> tauri build
✹ Building app...
       Error failed to get cargo metadata: No such file or directory (os error 2)
file:///opt/homebrew/lib/node_modules/pake-cli/dist/cli.js:373
                reject(new Error(`${code}`));
```

### Anything else?

using fish shell

**Comment by ZhouFyk** [comment]
I'm in the same situation. You can see that there are some prompts in front of the error message, and one of them is probably "If you want it to take effect, you may need to restart the shell" (which probably means this, because I didn't record the original text), so I restarted the shell once, no more errors, and it was successful. You can also try this way.

**Comment by d0sse** [comment]
Thanks, after reload works
