### ISSUE TITLE
[Bug] Suspicious network requests 

### ISSUE THREAD

**Issue by hgezim** [tw93/Pake#834]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.6.1

### System version

MacOS 14.6.1

### Node.js version

v18.20.4

### Minimal reproduce step

There are requests made to:

- bytelb.net
- cdngslb.com
- npmmirror.com
- rsproxy.cn

Why are are the first two being used? Why not use official npm and crates?

### What did you expect to see?

No weird requests

### What did you see instead?

Weird requests 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
Thank you for your feedback. This is because in China, many developers cannot access the rust installation package. Then I made a judgment. If accessing the official installation is very slow, I will use the https://rsproxy.cn capability provided by Byte to speed up the installation.

Maybe I will increase the restrictions here so that it won't affect everyone's use.、
